{% set name = "subversion" %}
{% set version = "1.14.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.apache.org/subversion/subversion-{{ version }}.tar.bz2
  sha256: e78a29e7766b8b7b354497d08f71a55641abc53675ce1875584781aae35644a1

build:
  number: 2
  number: 3
  skip: true  # [win or ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - gettext-tools
    - make
    - nasm
    - pkg-config  # [unix]
    - python
  host:
    - cyrus-sasl  # [unix]
    - expat
    - gnupg  # [unix]
    - libapr
    - libaprutil
    - libboost-headers
    - libdb
    - libintl-devel  # [not linux]
    - libtool  # [unix]
    - libmagic  # [unix]
    - libutf8proc
    - lz4-c
    - openssl
    - perl
    - serf  # [linux]
    - sqlite
    - swig
    - zlib
  run:
    - perl

test:
  commands:
    - svn --help
    - perl -e 'use SVN::Client; use SVN::Core;'

about:
  home: https://subversion.apache.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Enterprise-class centralized version control for the masses
  doc_url: https://subversion.apache.org/docs/
  dev_url: https://subversion.apache.org/source-code.html

extra:
  recipe-maintainers:
    - danielnachun
    - scopatz
    - zklaus
    - rfiorella
