{% set name = "subversion" %}
{% set version = "1.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.apache.org/subversion/subversion-{{ version }}.tar.bz2
  sha256: 949efd451a09435f7e8573574c71c7b71b194d844890fa49cd61d2262ea1a440

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - autoconf  # [unix]
    - gettext
    - libtool  # [unix]
    - pkg-config  # [unix]
    - nasm
    - make
    - python >=2.7,<3
  host:
    - libboost-headers
    - libapr
    - libaprutil
    - sqlite
    - zlib
    - openssl
    - libdb
    - lz4-c
    - libutf8proc
    - expat
    - gnupg  # [unix]
    - cyrus-sasl  # [unix]
    - libmagic  # [unix]
    - serf  # [linux]
    - swig
    - perl
  run:
    - libapr
    - libaprutil
    - gettext
    - expat
    - perl

test:
  commands:
    - svn --help
    - perl -e 'use SVN::Client; use SVN::Core;'

about:
  home: https://subversion.apache.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Enterprise-class centralized version control for the masses
  doc_url: https://subversion.apache.org/docs/
  dev_url: https://subversion.apache.org/source-code.html

extra:
  recipe-maintainers:
    - scopatz
    - zklaus
    - rfiorella
